# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: windows-latest

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Dev(285ec89b-c6b0-46a6-9758-a0bce37bd2da)'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az deployment group create \
        --resource-group music-video-builder \
        --template-file main.bicep \
        --parameters sqlAdministratorLogin=${env:SQLADMINISTRATORLOGIN} sqlAdministratorPassword=${env:SQLADMINISTRATORPASSWORD}
